#!/bin/bash
# Replace PATH-TO-YOUR-FILE-WITH-SENSITIVE-DATA with the file in your git
# repository
# Source: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

git filter-branch --force --index-filter \
    "git rm --cached --ignore-unmatch PATH-TO-YOUR-FILE-WITH-SENSITIVE-DATA" \
    --prune-empty --tag-name-filter cat -- --all
