#!bin/bash

# There's cases where even `git reflog` can't help you anymore. E.g. when you've
# `git reset --hard` some uncommitted changes. In this case, there may, however,
# be a slight chance that you can recover lost data in form of a commit using:

git fsck --lost-found
# Via: https://stackoverflow.com/a/6780036

