#!/bin/bash

# Symbolic links are a great way to import directories and whiles without
# copying them. Say you want to connect a front end and a back end, linking two
# directories can come in handy. From the back end directory, do:

ln -s -T ../frontend/dist ./public

# Mac users note that their ln doesn't feature a `-T` option. Downloading
# GNU's `ln` with homebrew can be an option. Use `gln` to have the -T option.
