#!/bin/bash

# To always use the correct user name, website and email when doing `npm init`,
# a configuration may be necessary. Many parameters can be configuered using
# `# `npm config`!
# A nice tutorial can be found here: https://codeburst.io/setting-global-npm-defaults-for-quick-starting-new-projects-ed06ed22edb3

# To see the current `npm config`, do:

npm config ls -al

# To set a specific npm config parameter, do:

npm config set <key> <value> -g
# Additionally, take a look at your ~/.npmrc.

# ---
# npm installs packages by default using its "semver range operator" ^
# In the past, it has lead to security vulnerabilities. To only allow npm to
# define packages given their exact version, we can use the following command:

npm config set save-exact true
# Docs: https://docs.npmjs.com/misc/config#save-exact

